name: Fetch and Format Gothamist Articles

on:
  workflow_dispatch:

jobs:
  fetch-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run fetch script
        run: node -e 'require("./src/scripts").getGothamistLinks()'

      - name: Test output file
        run: |
          echo "Running validation on src/gothamist-links.js..."
          node <<'EOF'
          import { readFileSync } from 'fs';

          const contents = readFileSync('src/gothamist-links.js', 'utf8');
          const arrayMatch = contents.match(/export const coverageLinksGothamist = (\[.*\]);/s);

          if (!arrayMatch) {
            throw new Error("Could not parse coverageLinksGothamist array from JS file.");
          }

          const links = eval(arrayMatch[1]);

          if (!Array.isArray(links)) throw new Error("Parsed value is not an array.");
          if (links.length !== 3) throw new Error(`Expected 3 links, but got ${links.length}.`);

          for (const [i, link] of links.entries()) {
            if (typeof link.text !== 'string' || link.text.length < 5) {
              throw new Error(`Link ${i + 1} has an invalid 'text' field: ${link.text}`);
            }
            if (typeof link.href !== 'string' || link.href.length < 6) {
              throw new Error(`Link ${i + 1} has an invalid 'href' field: ${link.href}`);
            }
          }

          console.log("✅ All tests passed.");
          EOF

      - name: Commit and push formatted JS file if changed
        if: success()
        run: |
          if git diff --quiet src/gothamist-links.js; then
            echo "No changes to commit.";
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add src/gothamist-links.js
            git commit -m "Update Gothamist's list of recent coverage articles"
            git push
          fi
